### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by ThatOneCalculator** [System64fumo/sysmenu#6]
How did you configure the animations as per the gifs shown on the README? I don't see any documentation around that, and there's no default animations for me.

**Comment by System64fumo** [comment]
@ThatOneCalculator Simple, Hyprland.

**Comment by System64fumo** [comment]
Unless you meant the slide up thing when starting it up?
That's just css, I've sadly removed that from my current config since i felt like the animations were a bit much.
If i can find them i'll let you know.

**Comment by System64fumo** [comment]
Could not find it, Either way it was a hack back then.
Not really a feature but i'd happily try to implement it properly if you wish.

In the meantime use this:
```css
#sysmenu .box_layout_inner {
	animation: animate 1s;
}

@keyframes animate {
	from {
		margin-top: 100px;
		opacity: 0.25;
	}
	to {
		margin-top: 0px;
		opacity: 1;
	}
}
```
